# Generated by Django 4.1.2 on 2024-04-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_af',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar_dz',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ast',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_be',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_bn',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_bs',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ca',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_cs',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_cy',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_da',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_dsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_el',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en_au',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en_gb',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_eo',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_co',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_mx',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_ni',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_ve',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_eu',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fy',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ga',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_gd',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_gl',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hi',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hr',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hu',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ia',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ig',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_io',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_is',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ka',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kab',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_km',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kn',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ko',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_lb',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_lv',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_mk',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ml',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_mr',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ms',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_my',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_nb',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ne',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_nn',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_os',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pa',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pl',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sk',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sl',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sq',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sr',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sr_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ta',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_te',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_th',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tk',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tt',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_udm',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ur',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_vi',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
    ]
