# Generated by Django 4.1.2 on 2024-04-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_title_af_remove_news_title_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
    ]
