# Generated by Django 4.1.2 on 2024-04-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_title_ky_news_title_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
    ]
