# Generated by Django 4.1.2 on 2024-04-25 08:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_pages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_head', models.CharField(max_length=255, verbose_name='Верхнее название')),
                ('title_head_ky', models.CharField(max_length=255, null=True, verbose_name='Верхнее название')),
                ('title_head_ru', models.CharField(max_length=255, null=True, verbose_name='Верхнее название')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('text_head', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('text_head_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
                ('text_head_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
            ],
        ),
    ]
