# Generated by Django 4.1.2 on 2024-04-25 08:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_admissionstudents_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudents',
            name='text_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='admissionstudents',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
    ]
