# Generated by Django 4.1.2 on 2024-04-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlesson',
            name='image',
            field=models.FileField(upload_to='media/class_lessons/', verbose_name='Файл'),
        ),
    ]
