# Generated by Django 4.1.2 on 2024-04-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_classlesson_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlesson',
            options={'verbose_name': 'Кружки', 'verbose_name_plural': 'Кружки'},
        ),
    ]
