# Generated by Django 4.1.2 on 2024-04-23 09:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='media/contingent/', verbose_name='Фотография')),
                ('grade', models.CharField(max_length=100, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Контингент',
                'verbose_name_plural': 'Контингент',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('image', models.ImageField(upload_to='media/teachers/', verbose_name='Фотография')),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Преподователи',
                'verbose_name_plural': 'Преподователи',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность')),
                ('duty', models.CharField(max_length=255, verbose_name='Обязанность')),
                ('requirements', models.CharField(max_length=255, verbose_name='Требования')),
                ('conditions', models.CharField(max_length=255, verbose_name='Условия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.numbers', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Вакансии',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/qualification/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Преподавтель')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификация',
            },
        ),
    ]
