# Generated by Django 4.1.2 on 2024-04-23 10:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingent',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='contingent',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='job_title_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='job_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='duty_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Обязанность'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='duty_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Обязанность'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Требования'),
        ),
    ]
